[FIX] better error messages and tips on connect

diff --git a/bin/launch b/bin/launch
--- a/bin/launch
+++ b/bin/launch
@@ -5,13 +5,21 @@ MAKERVERSE_HOME=${MAKERVERSE_HOME:-${HOME}}
 # Figure out where the git checkout directory lives, if any:
 if [[ -z "$MAKERVERSE_GIT_DIR" ]]; then
   if [[ $(which git) ]] && [[ $(git remote get-url origin) =~ "makerverse.git" ]]; then
-    MAKERVERSE_GIT_DIR=$(pwd)
+    # If launched from a Makerverse git directory.
+    MAKERVERSE_GIT_DIR="$(pwd)"
   else
-    MAKERVERSE_GIT_DIR="${MAKERVERSE_HOME}/makerverse"
+    # Otherwise, the parent directory of this script should (hopefully) work.
+    MAKERVERSE_GIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" && pwd)"
   fi
+fi
+if [[ ! -d "$MAKERVERSE_GIT_DIR" ]]; then
+  echo "Could not find the Makerverse installation at $MAKERVERSE_GIT_DIR"
+  echo "Please try downloading or cloning the project at this location."
+  exit 1
 fi
 MAKERVERSE_LAUNCH_METHOD=${MAKERVERSE_LAUNCH_METHOD:-docker}
 MAKERVERSE_SETTINGS_FILE="${MAKERVERSE_HOME}/.makerverse"
+MAKERVERSE_PORT="${MAKERVERSE_PORT:-8000}"
 
 # Scan dependency versions
 if [[ $(which node) ]]; then
@@ -112,7 +120,7 @@ createSettings() {
 
 # Main launch method
 launch() {
-  echo "Makerverse launching from ${MAKERVERSE_HOME}"
+  echo "Makerverse launching with home directory at ${MAKERVERSE_HOME} (project at: ${MAKERVERSE_GIT_DIR})"
 
   if [ "$1" = "node" ]; then
     createSettings ".makerverse.default"
@@ -133,7 +141,7 @@ launch() {
     checkout
     npm install
     npm run build-prod
-    node ./bin/makerverse
+    node ./bin/makerverse -p "${MAKERVERSE_PORT}"
   elif [ "$1" = "docker" ] || [ "$1" = "" ]; then
     createSettings ".makerverse.docker"
     # Launch via a docker image
@@ -154,8 +162,10 @@ launch() {
     echo "Killing prior instances..."
     docker kill makerverse || true
     echo "Launching $docker_img..."
-    docker run --rm --privileged --name makerverse -v /dev:/dev -p 8000:8000 \
+    docker run --rm --privileged --name makerverse -v /dev:/dev \
+      -p "${MAKERVERSE_PORT}:8000" \
       -v "$MAKERVERSE_SETTINGS_FILE:/home/node/.cncrc" \
+      -v "$MAKERVERSE_GIT_DIR:/home/node/makerverse" \
       "$docker_img"
   else
     echo "Invalid launch method: ${launch}"
